version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/node
permissions:
  - object: /home/ubuntu
    owner: ubuntu
    group: ubuntu
    type:
      - directory
      - file
hooks:
  BeforeInstall:
    - location: scripts/install.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/change_permissions.sh
      timeout: 600
      runas: ubuntu
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 120
      runas: ubuntu
  ApplicationStop:
    - location: scripts/stop.sh
      timeout: 120
      runas: ubuntu
